GCC=c:\WinAVR-20100110\bin\avr-gcc.exe
OBJCOPY=c:\WinAVR-20100110\bin\avr-objcopy.exe

main:
	GCC -Os -Wa,-gstabs -Ic:\WinAVR-20100110\include -mmcu=atxmega32a4 main.c -o zolkko-alarm.elf
	OBJCOPY -j .text -O ihex zolkko-alarm.elf zolkko-alarm.hex

